language: objective-c
rvm: system
osx_image: xcode7.3
install:
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo bundle install
  - brew uninstall --force brew-cask
  - travis_wait 30 sudo softwareupdate -a -i
script:
  - soloist
